//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SceneStudioApp.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SceneStudioApp.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap Arrow {
            get {
                object obj = ResourceManager.GetObject("Arrow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Camera {
            get {
                object obj = ResourceManager.GetObject("Camera", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deselects any selected objects..
        /// </summary>
        internal static string clearToolStripButton_help {
            get {
                return ResourceManager.GetString("clearToolStripButton_help", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap Copy {
            get {
                object obj = ResourceManager.GetObject("Copy", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copies the currently selected object. Insert these copies using &apos;Paste.&apos;.
        /// </summary>
        internal static string copyToolStripButton_help {
            get {
                return ResourceManager.GetString("copyToolStripButton_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deletes the currently selected object..
        /// </summary>
        internal static string deleteToolStripButton_help {
            get {
                return ResourceManager.GetString("deleteToolStripButton_help", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap Down {
            get {
                object obj = ResourceManager.GetObject("Down", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Erase {
            get {
                object obj = ResourceManager.GetObject("Erase", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Export {
            get {
                object obj = ResourceManager.GetObject("Export", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flips the currently selected object around so that a different side faces up.
        ///
        ///Use this to reorient objects that aren&apos;t facing the way they should..
        /// </summary>
        internal static string flipMToolStripButton_help {
            get {
                return ResourceManager.GetString("flipMToolStripButton_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flips the currently selected object around so that a different side faces up.
        ///
        ///Use this to reorient objects that aren&apos;t facing the way they should. .
        /// </summary>
        internal static string flipNToolStripButton_help {
            get {
                return ResourceManager.GetString("flipNToolStripButton_help", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap Help {
            get {
                object obj = ResourceManager.GetObject("Help", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Help_book {
            get {
                object obj = ResourceManager.GetObject("Help_book", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opens this window..
        /// </summary>
        internal static string helpToolStripButton_help {
            get {
                return ResourceManager.GetString("helpToolStripButton_help", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap Homepage {
            get {
                object obj = ResourceManager.GetObject("Homepage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;ve selected an object to put into the scene. Click the left mouse button to place the object..
        /// </summary>
        internal static string insertObject_help {
            get {
                return ResourceManager.GetString("insertObject_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Look around the scene.
        ///
        ///Mouse Button 1 Click-Drag = Pan
        ///Mouse Button 2 Click-Drag = Rotate
        ///Mouse Wheel = Zoom
        ///Shift + Mouse Button 1 Click-Drag = Zoom.
        /// </summary>
        internal static string lookAroundToolStripButton_help {
            get {
                return ResourceManager.GetString("lookAroundToolStripButton_help", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap Mouse_pointer {
            get {
                object obj = ResourceManager.GetObject("Mouse_pointer", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Move {
            get {
                object obj = ResourceManager.GetObject("Move", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move the currently selected object.
        ///
        ///Mouse Button 1 Click-Drag = Move on Surface
        ///Mouse Button 2 Click-Drag = Move Freely
        ///Shift +Mouse Button 2 Click-Drag = Levitate.
        /// </summary>
        internal static string moveToolStripButton_help {
            get {
                return ResourceManager.GetString("moveToolStripButton_help", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap New_file {
            get {
                object obj = ResourceManager.GetObject("New_file", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creates a new scene..
        /// </summary>
        internal static string newToolStripButton_help {
            get {
                return ResourceManager.GetString("newToolStripButton_help", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap No {
            get {
                object obj = ResourceManager.GetObject("No", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CONTROLLING THE CAMERA
        ///Orbit  -  Alt + Left Mouse Button
        ///Dolly  -  Alt + Right Mouse Button
        ///Zoom  -  Scroll Wheel
        ///
        ///SELECTING/MOVING OBJECTS
        ///Select  -  Left Mouse Button
        ///Move on Surfaces  -  Right Mouse Button
        ///Move in Plane  -  Shift + Right Mouse Button
        ///Levitate  -  Control + Right Mouse Button.
        /// </summary>
        internal static string normalMode_help {
            get {
                return ResourceManager.GetString("normalMode_help", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap Objects {
            get {
                object obj = ResourceManager.GetObject("Objects", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Open_file {
            get {
                object obj = ResourceManager.GetObject("Open_file", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opens a previously saved scene file..
        /// </summary>
        internal static string openToolStripButton_help {
            get {
                return ResourceManager.GetString("openToolStripButton_help", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap Paste {
            get {
                object obj = ResourceManager.GetObject("Paste", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inserts a new instance of the last copied model into the scene..
        /// </summary>
        internal static string pasteToolStripButton_help {
            get {
                return ResourceManager.GetString("pasteToolStripButton_help", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap Refresh {
            get {
                object obj = ResourceManager.GetObject("Refresh", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resets the camera to its original viewpoint..
        /// </summary>
        internal static string resetCameraToolStripButton_help {
            get {
                return ResourceManager.GetString("resetCameraToolStripButton_help", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap Revert {
            get {
                object obj = ResourceManager.GetObject("Revert", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resets all the rotations done to the currently selected object..
        /// </summary>
        internal static string revertObjectToolStripButton_help {
            get {
                return ResourceManager.GetString("revertObjectToolStripButton_help", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap Rotate_CCW {
            get {
                object obj = ResourceManager.GetObject("Rotate_CCW", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Rotate_CW {
            get {
                object obj = ResourceManager.GetObject("Rotate_CW", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Rotate_left {
            get {
                object obj = ResourceManager.GetObject("Rotate_left", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Rotate_right {
            get {
                object obj = ResourceManager.GetObject("Rotate_right", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rotates the currently selected object counter-clockwise.
        ///
        ///Hold &apos;Shift&apos; to rotate by smaller increments..
        /// </summary>
        internal static string rotateCCWToolStripButton_help {
            get {
                return ResourceManager.GetString("rotateCCWToolStripButton_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rotates the currently selected object clockwise.
        ///
        ///Hold &apos;Shift&apos; to rotate by smaller increments..
        /// </summary>
        internal static string rotateCWToolStripButton_help {
            get {
                return ResourceManager.GetString("rotateCWToolStripButton_help", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap Save {
            get {
                object obj = ResourceManager.GetObject("Save", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saves the current scene to a file..
        /// </summary>
        internal static string saveToolStripButton_help {
            get {
                return ResourceManager.GetString("saveToolStripButton_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decreases the size of the currently selected object.
        ///
        ///Hold &apos;Shift&apos; to scale by smaller increments..
        /// </summary>
        internal static string scaleDownToolStripButton_help {
            get {
                return ResourceManager.GetString("scaleDownToolStripButton_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Increases the size of the currently selected object.
        ///
        ///Hold &apos;Shift&apos; to scale by smaller increments..
        /// </summary>
        internal static string scaleUpToolStripButton_help {
            get {
                return ResourceManager.GetString("scaleUpToolStripButton_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select objects in the scene by clicking on them..
        /// </summary>
        internal static string selectToolStripButton_help {
            get {
                return ResourceManager.GetString("selectToolStripButton_help", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap Show {
            get {
                object obj = ResourceManager.GetObject("Show", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Target {
            get {
                object obj = ResourceManager.GetObject("Target", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Transparency {
            get {
                object obj = ResourceManager.GetObject("Transparency", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Undo {
            get {
                object obj = ResourceManager.GetObject("Undo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reverts recent actions..
        /// </summary>
        internal static string undoToolStripButton_help {
            get {
                return ResourceManager.GetString("undoToolStripButton_help", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap Up {
            get {
                object obj = ResourceManager.GetObject("Up", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Upload_image {
            get {
                object obj = ResourceManager.GetObject("Upload_image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uploads the current scene to our server and helps support our research!
        ///
        ///This will save your current scene.  Feel free to upload the same scene multiple times; only the latest version will be used..
        /// </summary>
        internal static string uploadToolStripButton_help {
            get {
                return ResourceManager.GetString("uploadToolStripButton_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launches the SceneStudio home page using your default web browswer.
        ///
        ///The home page contains information on the SceneStudio project, including a video tutorial..
        /// </summary>
        internal static string webPageToolStripButton_help {
            get {
                return ResourceManager.GetString("webPageToolStripButton_help", resourceCulture);
            }
        }
    }
}
